#define BUTTON_LAYOUT BUTTON_LAYOUT_BUTTONS_BASIC
#define BUTTON_LAYOUT_RIGHT BUTTON_LAYOUT_STICKLESSB


#define DEFAULT_INPUT_MODE INPUT_MODE_PS4
#define DEFAULT_DPAD_MODE DPAD_MODE_LEFT_ANALOG
#define DEFAULT_SOCD_MODE SOCD_MODE_FIRST_INPUT_PRIORITY


#define DEFAULT_FORCED_SETUP_MODE FORCED_SETUP_MODE_OFF


#define PIN_DPAD_UP 1
#define PIN_DPAD_DOWN 2
#define PIN_DPAD_LEFT 3
#define PIN_DPAD_RIGHT 4
#define PIN_BUTTON_B1 5
#define PIN_BUTTON_B2 6
#define PIN_BUTTON_B3 7
#define PIN_BUTTON_B4 8
#define PIN_BUTTON_R1 9
#define PIN_BUTTON_R2 10
#define PIN_BUTTON_L1 11
#define PIN_BUTTON_L2 12
#define PIN_BUTTON_S2 13
#define PIN_BUTTON_S1 14
#define PIN_BUTTON_A1 15
#define PIN_BUTTON_R3 16
#define PIN_BUTTON_L3 17
#define PIN_BUTTON_A2 18


#define GPIO_PIN_01 GpioAction::BUTTON_PRESS_UP
#define GPIO_PIN_02 GpioAction::BUTTON_PRESS_DOWN
#define GPIO_PIN_03 GpioAction::BUTTON_PRESS_LEFT
#define GPIO_PIN_04 GpioAction::BUTTON_PRESS_RIGHT
#define GPIO_PIN_05 GpioAction::BUTTON_PRESS_B1
#define GPIO_PIN_06 GpioAction::BUTTON_PRESS_B2
#define GPIO_PIN_07 GpioAction::BUTTON_PRESS_B3
#define GPIO_PIN_08 GpioAction::BUTTON_PRESS_B4
#define GPIO_PIN_09 GpioAction::BUTTON_PRESS_R1
#define GPIO_PIN_10 GpioAction::BUTTON_PRESS_R2
#define GPIO_PIN_11 GpioAction::BUTTON_PRESS_L1
#define GPIO_PIN_12 GpioAction::BUTTON_PRESS_L2
#define GPIO_PIN_13 GpioAction::BUTTON_PRESS_S2
#define GPIO_PIN_14 GpioAction::BUTTON_PRESS_S1
#define GPIO_PIN_15 GpioAction::BUTTON_PRESS_A1
#define GPIO_PIN_16 GpioAction::BUTTON_PRESS_R3
#define GPIO_PIN_17 GpioAction::BUTTON_PRESS_L3
#define GPIO_PIN_18 GpioAction::BUTTON_PRESS_A2
